language: android

jdk:
  - oraclejdk8

before_install:
  - if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
        openssl aes-256-cbc -K $encrypted_3327ea27a2f5_key -iv $encrypted_3327ea27a2f5_iv -in Bin.jks.enc -out Bin.jks -d;
    fi
  - gem install fir-cli

android:
  components:
    # https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
    - tools
    - tools
    - build-tools-25.0.1
    - android-25

script:
  - if [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
        ./gradlew assembleRelease --stacktrace;
    else
        ./gradlew assembleDebug  --stacktrace;
    fi


before_deploy:
  - export APK_PATH=$(ls app/build/outputs/apk/*-release.apk)

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $APK_PATH
  skip_cleanup: true
  overwrite: true
  on:
    tags: true

after_deploy:
   - fir p $APK_PATH -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"
